### PR TITLE
Change/input with events

### PR DESCRIPTION
**Pull request by KiwiLT**
## Description
Input controller now contains events instead of script references

## Setting up testing environment
1. In the project window navigate to Project/Assets/Scenes and open the InputEvents scene.
2. Press Play.

#### Testing the Anxiety Meter
Criteria:

- [x] All controls should work the same way they used to work

## Checklist
_These checks should always be true for your pull request_
- [x] My pull request is for one story/feature.
- [x] Every individual commit in this pull request is logical.
- [x] All code, documentation, commits and player seen texts are in English.
- [x] I have deleted unused / unnecessary code.
- [x] If my edits need a change in documentation, then I have updated the documentation.
- [x] All code is in correspondence with the code conventions.

### CODE REVIEW

**Comment by KiwiLT** [comment]
If you review please request changes then I add it to the game scene

**Comment by KiwiLT** [comment]
Didn't add it in the prefab yet, tell me if the code is correct then I change the prefab as well

**Review by Jeroenvn — APPROVED** [review]
looks good!

**Review by Jeroenvn — CHANGES_REQUESTED** [review]
some public variables in the starterassetsinputs are not in camel case

**Comment by KiwiLT** [comment]
changed the public variables and changed the prefab. works in gamescene.

**Review by Jeroenvn — APPROVED** [review]
Looks good!

**Pull request merged**
