### PR TITLE
fix: player cannot highlight himself

### LINKED ISSUE #71: Fix: Being able to highlight yourself
Criteria:
- When in possession aiming mode, you should not be able to highlight yourself

### PR DESCRIPTION
**Pull request by hassanmohamed2003**
## Description
When possesing object and going into possesion aim mode you wont highlight yourself

## Setting up testing environment
1. In the project window navigate to Project/Assets/Scenes and open the "Game" scene.
2. Press Play.

#### Fear reducer cooldown
Criteria:
- [x] when in aim mode possesion you dont highlight yourself

## Checklist
_These checks should always be true for your pull request_
- [x] My pull request is for one story/feature.
- [x] Every individual commit in this pull request is logical.
- [x] All code, documentation, commits and player seen texts are in English.
- [x] I have deleted unused / unnecessary code.
- [x] If my edits need a change in documentation, then I have updated the documentation.
- [x] All code is in correspondence with the code conventions.

### CODE REVIEW

**Review by Jeroenvn — CHANGES_REQUESTED** [review]
If the currentHighlight does not contain the throwable component you get an error.

**Review by Jeroenvn — DISMISSED** [review]
the check on the _currentHighlight is done before the current highlight is updated

**Review by dcsmit — APPROVED** [review]
Works as it should and requested changes were made.

**Review by dcsmit — APPROVED** [review]
Requested changes have been made

**Review by dcsmit — APPROVED** [review]
Requested changes have been made.

**Pull request merged**
